#!/bin/sh

set -e

JOURNAL_FILE=$HOME/journal.log
ENTRY_TEXT=""

echo "\n$(date +"[%Y/%m/%d] %B %d, %A: ")" >> "${JOURNAL_FILE}"

TMP=$(mktemp)
${EDITOR} ${TMP}
ENTRY_TEXT="$(cat ${TMP})\n"
rm ${TMP}

printf "${ENTRY_TEXT}" >> "${JOURNAL_FILE}"
